# Generated by Django 6.0.4 on 2026-04-11 05:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrepItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('ingredients', models.TextField(blank=True)),
                ('allergen_info', models.TextField(blank=True)),
                ('shelf_life_hours', models.PositiveIntegerField(default=24)),
                ('storage_notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prep_items', to='stores.department')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prep_items', to='stores.store')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('store', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PrepTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('prepared_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('printed', 'Printed'), ('completed', 'Completed'), ('discarded', 'Discarded')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('batch_code', models.CharField(blank=True, max_length=100)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prep_tasks', to='stores.department')),
                ('prep_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prep_tasks', to='prep.prepitem')),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_tasks', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prep_tasks', to='stores.store')),
            ],
            options={
                'ordering': ['-prepared_at'],
            },
        ),
    ]
