# Generated by Django 6.0.4 on 2026-04-11 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prep', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label_title', models.CharField(max_length=255)),
                ('label_body', models.TextField(blank=True)),
                ('ai_generated_text', models.TextField(blank=True)),
                ('qr_payload', models.TextField(blank=True)),
                ('paper_size', models.CharField(blank=True, max_length=20)),
                ('rendered_html', models.TextField(blank=True)),
                ('prep_task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='label', to='prep.preptask')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('printed', 'Printed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('printer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_jobs', to='stores.printer')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_jobs_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrintJobItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('copies', models.PositiveIntegerField(default=1)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_job_items', to='labels.label')),
                ('print_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='labels.printjob')),
            ],
            options={
                'unique_together': {('print_job', 'label')},
            },
        ),
    ]
