# Generated by Django 5.2.13 on 2026-04-16 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('driver_type', models.CharField(choices=[('mock_file', 'Mock File'), ('raw_tcp', 'Raw TCP'), ('zpl', 'Zebra ZPL'), ('html_preview', 'HTML Preview'), ('pdf_file', 'PDF File'), ('windows_spooler', 'Windows Spooler')], default='mock_file', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('port', models.PositiveIntegerField(default=9100)),
                ('device_name', models.CharField(blank=True, help_text='OS-visible printer/spooler name when applicable', max_length=255)),
                ('paper_size', models.CharField(choices=[('2x1', '2" x 1"'), ('3x2', '3" x 2"'), ('4x2', '4" x 2"'), ('custom', 'Custom')], default='4x2', max_length=20)),
                ('dpi', models.PositiveIntegerField(default=203)),
                ('connection_options', models.JSONField(blank=True, default=dict, help_text='Driver-specific options like timeouts, queue names, media settings, etc.')),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printers', to='stores.store')),
            ],
            options={
                'ordering': ['store__name', 'name'],
                'unique_together': {('store', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='stores.store')),
            ],
            options={
                'ordering': ['store__name', 'name'],
                'unique_together': {('store', 'name')},
            },
        ),
    ]
