# Generated by Django 5.2.13 on 2026-04-12 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='connection_options',
            field=models.JSONField(blank=True, default=dict, help_text='Driver-specific options like timeouts, queue names, media settings, etc.'),
        ),
        migrations.AddField(
            model_name='printer',
            name='device_name',
            field=models.CharField(blank=True, help_text='OS-visible printer/spooler name when applicable', max_length=255),
        ),
        migrations.AddField(
            model_name='printer',
            name='driver_type',
            field=models.CharField(choices=[('mock_file', 'Mock File'), ('raw_tcp', 'Raw TCP'), ('zpl', 'Zebra ZPL'), ('html_preview', 'HTML Preview'), ('pdf_file', 'PDF File'), ('windows_spooler', 'Windows Spooler')], default='mock_file', max_length=50),
        ),
    ]
